integration:
  citizen:
    connectTimeout: 5
    readTimeout: 30
  citizenmapping:
    connectTimeout: 5
    readTimeout: 30
  legalentity:
    connectTimeout: 5
    readTimeout: 30
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      citizen:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      citizenmapping:
        ignoreExceptions: 'se.sundsvall.dept44.exception.ClientProblem    '
      legalentity:
        ignoreExceptions: 'se.sundsvall.dept44.exception.ClientProblem    '
spring:
  application:
    name: api-party
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
          citizenmapping:
            authorization-grant-type: client_credentials
            provider: citizenmapping
          legalentity:
            authorization-grant-type: client_credentials
            provider: legalentity
springdoc:
  swagger-ui:
    operationsSorter: method
