integration:
  citizen:
    url: http://localhost:${wiremock.server.port:}/api-citizen
  legalentity:
    url: http://localhost:${wiremock.server.port:}/api-legalentity
spring:
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          legalentity:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          legalentity:
            client-id: the-client-id
            client-secret: the-client-secret
