integration:
  citizen:
    url: http://localhost:${wiremock.server.port:}/api-citizen
  legalentity:
    url: http://localhost:${wiremock.server.port:}/api-legalentity
spring:
  autoconfigure:
    exclude: #Because dept44-starter-test pulls spring-boot-starter-data-jpa
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          legalentity:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          legalentity:
            client-id: the-client-id
            client-secret: the-client-secret
